// Este archivo contiene la lista de logos de servicios populares para automatización.
// Puedes agregar más rutas de imágenes en la carpeta public/images/ para ampliar el efecto visual.

export const MODULE_LOGOS = [
  { name: 'Gmail', src: '/images/gmail.svg' },
  { name: 'Google Drive', src: '/images/googledrive.svg' },
  { name: 'Google Calendar', src: '/images/googlecalendar.svg' },
  { name: 'Google Meet', src: '/images/googlemeet.svg' },
  { name: 'Google Contacts', src: '/images/googlecontacts.svg' },
  { name: 'Google Sheets', src: '/images/googlesheets.svg' },
  { name: 'Google Docs', src: '/images/googledocs.svg' },
  { name: 'Google Slides', src: '/images/googleslides.svg' },
  { name: 'Google Forms', src: '/images/googleforms.svg' },
  { name: 'Google Keep', src: '/images/googlekeep.svg' },
  { name: 'Google Gemini', src: '/images/google-gemini.svg' },
  { name: 'Vertex AI', src: '/images/vertex-ai.svg' },
  { name: 'Google Bard', src: '/images/google-bard.svg' },
  { name: 'Duet AI', src: '/images/duet-ai.svg' },
  { name: 'Google Cloud', src: '/images/google-cloud.svg' },
  { name: 'Google Maps', src: '/images/googlemaps.svg' },
  { name: 'YouTube', src: '/images/youtube.svg' },
  { name: 'Google Ads', src: '/images/googleads.svg' },
  { name: 'Google Analytics', src: '/images/googleanalytics.svg' },
  { name: 'Google Tag Manager', src: '/images/googletagmanager.svg' },
  { name: 'Google News', src: '/images/googlenews.svg' },
  { name: 'Google Photos', src: '/images/googlephotos.svg' },
  { name: 'Google Play', src: '/images/googleplay.svg' },
  { name: 'Google Podcasts', src: '/images/googlepodcasts.svg' },
  { name: 'Google Classroom', src: '/images/googleclassroom.svg' },
  { name: 'Google Domains', src: '/images/googledomains.svg' },
  { name: 'Google Translate', src: '/images/googletranslate.svg' },
  { name: 'Google Shopping', src: '/images/googleshopping.svg' },
  { name: 'Google Flights', src: '/images/googleflights.svg' },
  { name: 'Google Finance', src: '/images/googlefinance.svg' },
  { name: 'Google Earth', src: '/images/googleearth.svg' },
  { name: 'Google Workspace', src: '/images/googleworkspace.svg' },
  { name: 'Google Assistant', src: '/images/googleassistant.svg' },
  { name: 'Google Home', src: '/images/googlehome.svg' },
  { name: 'Google Fit', src: '/images/googlefit.svg' },
  { name: 'Google Family Link', src: '/images/googlefamilylink.svg' },
];
