export const TYPES = {
    HistoryService: Symbol.for('HistoryService'),
    AlertingService: Symbol.for('AlertingService'),
    SystemMetricsService: Symbol.for('SystemMetricsService'),
    TelegramService: Symbol.for('TelegramService'),
    GoogleSecretManagerService: Symbol.for('GoogleSecretManagerService'),
    CredentialManagerService: Symbol.for('CredentialManagerService'),
    SystemHealthService: Symbol.for('SystemHealthService'),
    DatabaseHealthService: Symbol.for('DatabaseHealthService'),
    EmailService: Symbol.for('EmailService'),
    AuthService: Symbol.for('AuthService'),
    StripeService: Symbol.for('StripeService'),
    LinkedInService: Symbol.for('LinkedInService'),
    InstagramService: Symbol.for('InstagramService'),
    TikTokService: Symbol.for('TikTokService'),
    XService: Symbol.for('XService'),
    VertexAIService: Symbol.for('VertexAIService'),
    RagService: Symbol.for('RagService'),
    AnalyticsService: Symbol.for('AnalyticsService'),
    DockerService: Symbol.for('DockerService'),
    AIService: Symbol.for('AIService'),
    SearchService: Symbol.for('SearchService'),
    GoogleDriveService: Symbol.for('GoogleDriveService'),
    BackupService: Symbol.for('BackupService'),
};
