@echo off
REM Generated by trunk tool 'actionlint'
set PATH=C:\Users\Alejandro\AppData\Local\trunk\tools\actionlint\1.7.9-1b7910ae453de7b8f8eb3cc122ef9d21;C:\Users\Alejandro\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Alejandro\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b actionlint %*
