@echo off
REM Generated by trunk tool 'black'
set PATH=C:\Users\Alejandro\AppData\Local\trunk\tools\black\25.11.0-d65f406eab569af33bc28db9ac88a262/bin;C:\Users\Alejandro\AppData\Local\trunk\tools\black\25.11.0-d65f406eab569af33bc28db9ac88a262/Scripts;C:\Users\Alejandro\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070/bin;C:\Users\Alejandro\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070;C:\Users\Alejandro\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Alejandro\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set HOME=%HOME%
if not defined HOME set HOME=
set PYTHONUTF8=1
set VIRTUAL_ENV=C:\Users\Alejandro\AppData\Local\trunk\tools\black\25.11.0-d65f406eab569af33bc28db9ac88a262

start /w /b black %*
