@echo off
REM Generated by trunk tool 'dotenv-linter'
set PATH=C:\Users\Alejandro\AppData\Local\trunk\tools\dotenv-linter\4.0.0-fc76d2c272371be7a10fc204fa3e0828;C:\Users\Alejandro\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Alejandro\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b dotenv-linter %*
