@echo off
REM Generated by trunk tool 'osv-scanner'
set PATH=C:\Users\Alejandro\AppData\Local\trunk\tools\osv-scanner\2.3.0-387241510943ceda2907624a5781d5d5;C:\Users\Alejandro\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Alejandro\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b osv-scanner %*
