@echo off
REM Generated by trunk tool 'svgo'
set HOME=%HOME%
if not defined HOME set HOME=
set PATH=C:\Users\Alejandro\AppData\Local\trunk\tools\svgo\4.0.0-8edc929c1e1ba879ba5c8f86d2394430/node_modules/.bin;C:\Users\Alejandro\AppData\Local\trunk\tools\node\22.16.0-12da8a4c27b144aedaf7d975e067667c/bin;C:\Users\Alejandro\AppData\Local\trunk\tools\node\22.16.0-12da8a4c27b144aedaf7d975e067667c;C:\Users\Alejandro\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Alejandro\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set NODE_PATH=C:\Users\Alejandro\AppData\Local\trunk\tools\svgo\4.0.0-8edc929c1e1ba879ba5c8f86d2394430/node_modules

start /w /b svgo %*
