@echo off
REM Generated by trunk tool 'trufflehog'
set PATH=C:\Users\Alejandro\AppData\Local\trunk\tools\trufflehog\3.91.2-0c453de68537e786d8ec7a126ca0d50e;C:\Users\Alejandro\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Alejandro\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b trufflehog %*
