action_id: trunk-cache-prune
date: 2025-12-07 14:25:40
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1765117540
full_timestamp:
  nanos: 935529000
  seconds: 1765117540
trunk_version: 1.25.0
