action_id: trunk-share-with-everyone
date: 2025-12-07 14:25:39
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-share-with-everyone\r\n"
  err: ""
timestamp: 1765117539
full_timestamp:
  nanos: 276476000
  seconds: 1765117539
trunk_version: 1.25.0
action_output:
  notifications_to_delete:
    - trunk-share-with-everyone
